---
title: "FCC Data Acquisition"
author: "Kateryna Savchyn"
date: "6/19/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## FCC Form 477

Resource:[Form 477](https://opendata.fcc.gov/Wireline/Fixed-Broadband-Deployment-Data-Dec-2017-Status-V2/ei6b-6aiz)
Updated: April 8, 2019
Type: CSV

```{r load packages}
for (pkg in c("httr", "here", "maptools","gpclib","sp", 'sf', 'ggplot2', 'ggmap', 'osmdata', 'tidyverse', 'tigris', 'acs', "RSocrata")) {
  library(pkg, character.only = TRUE)
}
```

```{r fcc 477, message=FALSE}


fcc_477 <- function(state) {
  destfile <- here("data", "original", "FCC",sprintf('fcc_477_%s.csv', state))
  if (!file.exists(destfile)) {
    df <- read.socrata(
  sprintf("https://opendata.fcc.gov/resource/ei6b-6aiz.csv?stateabbr=%s",state),
  app_token = Sys.getenv("fcc_app_token"),
  email     = "ksvchn@gmail.com",
  password  = Sys.getenv("fcc_api_pwd")
)
  write.csv(df,  destfile)
  }
}

# get data files for each state
for (state in state.abb) {
  fcc_477(state)
}



```

## FCC Residential Fixed Internet Access Service Connections
Resource:[Internet Access  Service Connections](https://www.fcc.gov/reports-research/maps/residential-fixed-internet-access-service-connections-per-1000-households-by-census-tract/)
Updated: June, 2017
Type: zip


```{r int serv report}
service_map <- function() {
  destzip<- here("data", "original", "FCC", "tract_map_jun_2017.zip")
  destfile<- here("data", "original", "FCC", "tract_map_jun_2017.csv")
  if (!file.exists(destfile)) {
    download.file(url = "https://www.fcc.gov/sites/default/files/tract_map_jun_2017.zip",
                  destfile = destzip)
  }
  unzip(destzip, exdir = destfile)
}

service_map()

```

```{r census tracts}
state_blocks <- function(fips) {
  destzip <- here("data", "original", "Census Blocks",  '%s_census_blocks')
  destfile<- here("data", "original", "Census Blocks", sprintf('%s_census_blocks', fips))
  if (!file.exists(destfile)) {
    download.file(url = sprintf('https://www2.census.gov/geo/tiger/TIGER2018/BG/tl_2018_%s_bg.zip', fips),
                  destfile = destzip)
  }
  unzip(destzip, exdir = destfile)
}


# get block groups for VA
state_blocks(51)

```


```{r previous years - fcc}
## Tried and failed - historic files are corrupt

links <- c('http://transition.fcc.gov/form477/BroadbandData/Fixed/Dec16/Version%202/US-Fixed-without-satellite-Dec2016.zip','http://transition.fcc.gov/form477/BroadbandData/Fixed/Dec15/Version%204/US-Fixed-without-Satellite-Dec2015.zip','http://transition.fcc.gov/form477/BroadbandData/Fixed/Dec14/Version%203/US-Fixed-without-Satellite-Dec2014.zip')

links2 <- c('http://transition.fcc.gov/form477/BroadbandData/Fixed/Jun16/Version%202/US-Fixed-without-Satellite-Jun2016.zip',
                'http://transition.fcc.gov/form477/BroadbandData/Fixed/Dec15/Version%204/US-Fixed-without-Satellite-Dec2015.zip',
                'http://transition.fcc.gov/form477/BroadbandData/Fixed/Dec14/Version2/US-Fixed-without-Satellite-Dec2014.zip')

years <- c(2016, 2015, 2014)

df <- as.data.frame(cbind(years, links, links2))

fcc_history <- function(year){
  destzip <- here("data", "original", "FCC", "FCC_Historic",  sprintf('%s_fcc.zip', year))
  destfolder<- here("data", "original", "FCC", "FCC_Historic", sprintf('%s_fcc', year))
  if (!file.exists(destzip)) {
    download.file(url = as.character(df$links2[df$year == year]),
                  destfile = destzip)
  }
  zip::unzip(destzip, exdir = destfolder)
}

# fcc_history(2015) 
# <- Warning message:
#In unzip(destzip, exdir = destfile) : zip file is corrupt

# fcc_history(2015)

```
